defmodule DirGraph.Weaver do
  @moduledoc """
  The final stage of the Semantic Code Slicing pipeline.
  Takes a constrained JSON diff payload generated by the LLM
  and safely "plops" the mutations back into the raw source code
  using the original Node line numbers, preserving surrounding formatting. 
  """

  @doc """
  Applies an LLM-generated mutation payload to a source file.

  Expected `diff_payload` format:
  ```json
  {
    "mutations": [
      {
        "node_id": "Call:DB.Session.verify:L6",
        "action": "replace",
        "new_code": "Jwks.verify(parsed)"
      }
    ]
  }
  ```
  """
  def apply_diff(file_path, graph, diff_payload) do
    mutations = diff_payload["mutations"] || []

    # Validate all node IDs exist BEFORE reading the file so a bad node_id
    # raises a clean RuntimeError rather than a confusing File.Error.
    Enum.each(mutations, fn mut -> get_node(graph, mut["node_id"]) end)

    lines =
      File.read!(file_path)
      |> String.split("\n")

    # Sort mutations in reverse line order so that modifying a line
    # doesn't mess up the line indexes of subsequent mutations above it.
    sorted_mutations =
      mutations
      |> Enum.map(fn mut ->
        node = get_node(graph, mut["node_id"])
        line = Map.get(node, :line) || mut["line"] || 1
        end_line = Map.get(node, :end_line) || mut["end_line"] || line

        mut
        |> Map.put("line", line)
        |> Map.put("end_line", end_line)
      end)
      |> Enum.sort_by(& &1["line"], :desc)

    new_lines = execute_mutations(lines, sorted_mutations)

    new_source = Enum.join(new_lines, "\n")

    case verify_syntax(file_path, new_source) do
      :ok ->
        File.write!(file_path, new_source)
        {:ok, new_source}

      {:error, reason} ->
        {:error, {:syntax_error, reason, new_source}}
    end
  end

  # Verify syntax before writing. Currently covers Elixir; other languages pass through.
  defp verify_syntax(file_path, source) do
    case Path.extname(file_path) do
      ext when ext in ~w(.ex .exs) ->
        case Code.string_to_quoted(source) do
          {:ok, _} ->
            :ok

          {:error, {_meta, msg, token}} ->
            # Elixir 1.15+ returns msg as a {prefix, suffix} tuple; older versions
            # return a plain string. Normalise both to a printable string.
            str = fn
              v when is_binary(v) -> v
              v when is_tuple(v) -> v |> Tuple.to_list() |> Enum.join()
              v -> inspect(v)
            end

            {:error, str.(msg) <> str.(token)}
        end

      _ ->
        :ok
    end
  end

  defp get_node(graph, node_id) do
    case DirGraph.Graph.get_label(graph, node_id) do
      nil ->
        raise "Node '#{node_id}' not found in graph. Was the graph indexed before calling apply_diff?"

      label ->
        label
    end
  end

  defp execute_mutations(lines, []), do: lines

  defp execute_mutations(lines, [mutation | rest]) do
    # Line numbers from AST are 1-indexed, Elixir lists are 0-indexed.
    # We must ensure target_idx is valid.
    target_idx = max(0, mutation["line"] - 1)
    original_line = Enum.at(lines, target_idx) || ""

    lines =
      case mutation["action"] do
        "replace" ->
          [indentation] = Regex.run(~r/^\s*/, original_line) || [""]
          new_line = indentation <> mutation["new_code"]
          List.replace_at(lines, target_idx, new_line)

        "replace_node" ->
          # Replaces an entire multi-line block from `line` to `end_line`
          end_idx = max(0, mutation["end_line"] - 1)

          # Indentation is based on the first line of the targeted node
          [indentation] = Regex.run(~r/^\s*/, original_line) || [""]

          # We expect the LLM to provide multi-line new_code without parent indent
          indented_new_code =
            mutation["new_code"]
            |> String.split("\n")
            |> Enum.map(fn
              "" -> ""
              sub_line -> indentation <> sub_line
            end)
            |> Enum.join("\n")

          # Slice out the old lines and insert the new single string
          prefix = Enum.take(lines, target_idx)
          suffix = Enum.drop(lines, end_idx + 1)

          prefix ++ [indented_new_code] ++ suffix

        "delete" ->
          List.delete_at(lines, target_idx)

        "insert_after" ->
          [indentation] = Regex.run(~r/^\s*/, original_line) || [""]
          new_line = indentation <> mutation["new_code"]
          List.insert_at(lines, target_idx + 1, new_line)
      end

    execute_mutations(lines, rest)
  end
end
